# Permalinks
permalink: /:title/
relative_permalinks: false

show_excerpts: false  # set to true to show excerpts on the homepage

# Setup
title: John Holden

author:
  name: John Holden

# Manually added build settings
google_analytics: G-KQ366G044B

# Custom vars
theme: minima

minima:
  # generate social links in footer


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
header_pages:
 - about.md
